language: python

python:
- 3.7.9

os: linux

dist: xenial

addons:
  sonarcloud:
    organization: fernandoravagnani
    token: ${SONAR_TOKEN}

before_install:
- openssl aes-256-cbc -K $encrypted_2a8883044617_key -iv $encrypted_2a8883044617_iv
  -in lab-devopscloud-fer-ravagnani-4d310d8fb8dd.json.enc -out ../lab-devopscloud-fer-ravagnani-4d310d8fb8dd.json
  -d

jobs:
  include:
    - stage: Build
      name: "Testes Unitarios & Analise Sonar"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Define o script de teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - python -m unittest -v test || travis_terminate 1;
        - sonar-scanner || travis_terminate 1;

    - stage: STG Deploy
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab2-fernandoravagnani
        on:
          branch: main

    - stage: STG TEST
      script:
        - curl https://devopslab2-fernandoravagnani.herokuapp.com/ | grep Hello || travis_terminate 1;

    - stage: PROD Deploy
      script: skip
      # Definir o Deploy no Google Cloud
      deploy:
        provider: gae
        keyfile: "../lab-devopscloud-fer-ravagnani-4d310d8fb8dd.json"
        project: lab-devopscloud-fer-ravagnani
        on:
          branch: main

    - stage: PROD TEST
      script:
        - curl https://lab-devopscloud-fer-ravagnani.uc.r.appspot.com/ | grep Hello || travis_terminate 1;
