language: python

python:
- 3.7.9

os: linux

dist: xenial

install:
- pip install flask

script:
- python -m unittest -v test

before_install:
- openssl aes-256-cbc -K $encrypted_2a8883044617_key -iv $encrypted_2a8883044617_iv
  -in lab-devopscloud-fer-ravagnani-4d310d8fb8dd.json.enc -out ../lab-devopscloud-fer-ravagnani-4d310d8fb8dd.json
  -d

deploy:
- provider: heroku
  strategy: api
  api_key: "$HEROKU_API_KEY"
  edge: true
  app: devopslab2-fernandoravagnani
  on:
    branch: main
- provider: gae
  keyfile: "../lab-devopscloud-fer-ravagnani-4d310d8fb8dd.json"
  project: lab-devopscloud-fer-ravagnani
  on:
    branch: main
